# Generated by Django 5.2.1 on 2025-05-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('temp_avg', models.FloatField()),
                ('temp_min', models.FloatField()),
                ('temp_max', models.FloatField()),
                ('pressure_avg', models.FloatField()),
                ('pressure_min', models.FloatField()),
                ('pressure_max', models.FloatField()),
                ('humidity_avg', models.FloatField()),
                ('humidity_min', models.FloatField()),
                ('humidity_max', models.FloatField()),
                ('wind_avg', models.FloatField()),
                ('cloudiness', models.FloatField()),
            ],
        ),
    ]
