# Generated by Django 5.2.1 on 2025-05-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_weatherreading_alter_weatherdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
